services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - "grafana_storage:/var/lib/grafana"
    networks:
      - fastapi_network
  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/mydb
      API_KEY: /run/secrets/api_key
    secrets:
      - api_key
    container_name: fastapi_app
    depends_on:
      postgres:
        condition: service_healthy
    expose:
      - "8000"
    networks:
      - fastapi_network
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - fastapi_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi
    networks:
      - fastapi_network

secrets:
  api_key:
    file: api_key.txt

volumes:
  postgres_data:
    driver: local
  grafana_storage:
    driver: local

networks:
  fastapi_network:
    name: fastapi_network
    driver: bridge
